---
- hosts: exemplo
  remote_user: matheus
  become: yes
  tasks:
      - name: "Executa o container MySQL"
        docker_container:
          name: banco
          image: mysql:latest
          env:
            MYSQL_ROOT_PASSWORD: senha123
      - name: "Executa o container WordPress"
        docker_container:
          name: wordpress
          image: wordpress
          links:
            - "banco:mysql"
          ports:
            - "80:80"
  
